### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by tiziodcaio**
From 2.5 to 3.0

### CODE REVIEW

**Comment by luca020400** [comment]
Did anything change?
Or it's for the sake of using the "latest"

**Comment by luca020400** [comment]
Should've opted for Apache 2.0 from the beginning.
Just my two cents :)

**Comment by tiziodcaio** [comment]
It's the "latest" mania ;-)

**Comment by tiziodcaio** [comment]
I talked with an other developer, and in the summer maybe we'll try to update something...

**Comment by luca020400** [comment]
Ok thanks.
License shouldn't just change for the sake of change.
That's for a future reference.

**Comment by marco-bor** [comment]
TIL.

**Pull request merged**
